import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1 },
  container: { flex: 1 },
  floatingMenu: { position: 'absolute', left: 14, zIndex: 5 },
  floatingMenuButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  floatingActions: { position: 'absolute', right: 14, zIndex: 5 },
  floatingActionsGroup: {
    height: 48,
    paddingHorizontal: 3,
    borderRadius: 24,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    alignItems: 'center',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  actionBubble: {
    position: 'absolute',
    right: 0,
    top: 56,
    minWidth: 190,
    borderWidth: 1,
    borderRadius: 14,
    paddingVertical: 5,
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 7,
  },
  actionBubbleItem: {
    minHeight: 42,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 10,
  },
  actionBubbleText: { fontSize: 13, fontWeight: '600' },
  actionDivider: { width: StyleSheet.hairlineWidth, height: 20 },
  surfaceButton: {
    minHeight: 46,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 9,
  },
  auraMark: { alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  auraMarkImage: { width: '100%', height: '100%' },
  iconButton: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center', borderRadius: 18 },
  pressed: { opacity: 0.65 },
  conversation: { flex: 1 },
  conversationContent: { paddingHorizontal: 18, gap: 18 },
  firstMessageClearance: { paddingTop: 78 },
  emptyConversation: { flexGrow: 1 },
  emptyState: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 6, paddingVertical: 30 },
  welcomeTitle: { fontSize: 28, lineHeight: 35, fontWeight: '700', marginTop: 20, letterSpacing: -0.3 },
  welcomeSubtitle: { fontSize: 16, marginTop: 6 },
  suggestions: { width: '100%', gap: 10, marginTop: 32 },
  suggestionText: { fontSize: 14, fontWeight: '600' },
  noModelCard: { width: '100%', borderWidth: 1, borderRadius: 18, padding: 16, marginTop: 28, gap: 8 },
  noModelTitle: { fontSize: 15, fontWeight: '700' },
  noModelText: { fontSize: 13, lineHeight: 19 },
  messageRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 9 },
  userRow: { justifyContent: 'flex-end' },
  assistantRow: { justifyContent: 'flex-start' },
  messageColumn: { maxWidth: '84%', gap: 4 },
  bubble: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 20,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  userBubble: { borderBottomRightRadius: 6 },
  assistantBubble: { borderWidth: 1, borderBottomLeftRadius: 6 },
  messageText: { fontSize: 15, lineHeight: 23 },
  assistantHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 5 },
  assistantName: { fontSize: 13, fontWeight: '700', letterSpacing: 0.2 },
  assistantStatusDot: { width: 5, height: 5, borderRadius: 3 },
  assistantMeta: { fontSize: 11 },
  assistantMessageText: { fontSize: 15, lineHeight: 24, paddingRight: 4 },
  copyButton: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 5, paddingVertical: 4, paddingHorizontal: 5 },
  copyText: { fontSize: 12, fontWeight: '600' },
  typingBubble: {
    minWidth: 66,
    paddingHorizontal: 16,
    paddingVertical: 15,
    borderRadius: 19,
    flexDirection: 'row',
    gap: 5,
    borderWidth: 1,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  typingDot: { width: 6, height: 6, borderRadius: 3 },
  thinkingRow: { flexDirection: 'row', alignItems: 'center', gap: 5, minHeight: 25 },
  thinkingText: { fontSize: 13, fontStyle: 'italic', marginRight: 3 },
  composerArea: { paddingHorizontal: 14, paddingTop: 8 },
  composer: {
    minHeight: 56,
    maxHeight: 140,
    borderWidth: 1,
    borderRadius: 22,
    paddingHorizontal: 6,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'flex-end',
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  input: { flex: 1, fontSize: 15, lineHeight: 21, minHeight: 42, maxHeight: 120, paddingHorizontal: 7, paddingTop: 10, paddingBottom: 9 },
  plus: { fontSize: 27, lineHeight: 28, fontWeight: '300' },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  disclaimer: { fontSize: 10, textAlign: 'center', marginTop: 8, marginBottom: 1 },
  drawerRoot: { flex: 1, flexDirection: 'row' },
  // Backdrop is a separate absolutely-positioned layer so it can fade
  // independently of the drawer's slide-in transform.
  drawerBackdropWrap: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, zIndex: 1 },
  drawerBackdrop: { flex: 1 },
  drawer: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    maxWidth: 320,
    paddingHorizontal: 0,
    paddingTop: 0,
    borderRightWidth: StyleSheet.hairlineWidth,
    zIndex: 2,
    shadowOpacity: 0.18,
    shadowRadius: 20,
    shadowOffset: { width: 6, height: 0 },
    elevation: 8,
  },
  drawerSurface: { flex: 1, paddingHorizontal: 18, paddingTop: 102, backgroundColor: 'transparent' },
  drawerFadeTop: { position: 'absolute', left: 0, right: 0, top: 0, height: 92, opacity: 0.9, zIndex: 3 },
  drawerFadeBottom: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 76, opacity: 0.9, zIndex: 3 },
  drawerHeader: { position: 'absolute', left: 18, right: 18, top: 54, zIndex: 4, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  drawerTitle: { fontSize: 28, fontWeight: '800', letterSpacing: 2.2 },
  drawerSubtitle: { fontSize: 11, marginTop: 2 },
  searchBox: { height: 43, borderWidth: 1, borderRadius: 12, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 11, marginTop: 15 },
  searchInput: { flex: 1, fontSize: 13, paddingHorizontal: 8, paddingVertical: 0 },
  menuSectionLabel: { fontSize: 10, fontWeight: '800', letterSpacing: 1.2, marginTop: 10, marginBottom: 8, paddingHorizontal: 4 },
  drawerScroll: { flex: 1, minHeight: 0 },
  drawerRecentContent: { paddingBottom: 72 },
  drawerItem: { minHeight: 48, borderRadius: 11, flexDirection: 'row', alignItems: 'center', gap: 13, paddingHorizontal: 10 },
  drawerItemText: { fontSize: 14, fontWeight: '600' },
  conversationItemCopy: { flex: 1 },
  conversationPreview: { fontSize: 11, marginTop: 2 },
  emptyHistory: { fontSize: 12, paddingHorizontal: 10, paddingVertical: 8 },
  drawerFooter: { position: 'absolute', left: 18, right: 18, bottom: 0, zIndex: 4, paddingVertical: 18, backgroundColor: 'transparent' },
  modelWidget: { flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderRadius: 16, padding: 10 },
  modelBadge: { width: 36, height: 36, borderRadius: 18, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  modelCopy: { flex: 1 },
  drawerFooterTitle: { fontSize: 12, fontWeight: '700' },
  drawerFooterText: { fontSize: 11, lineHeight: 15, marginTop: 4 },
  sheetBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.3)', justifyContent: 'flex-end' },
  modelSheet: { borderTopLeftRadius: 26, borderTopRightRadius: 26, paddingHorizontal: 18, paddingTop: 10, paddingBottom: 28 },
  modelSheetHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 18 },
  modelDescription: { fontSize: 13, lineHeight: 19, maxWidth: 280, marginTop: -8 },
  modelOption: { minHeight: 72, borderWidth: 1, borderRadius: 16, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 10 },
  modelOptionIcon: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  modelOptionCopy: { flex: 1 },
  modelSizeBadge: { borderRadius: 8, paddingHorizontal: 7, paddingVertical: 5, marginRight: 2 },
  modelSizeText: { fontSize: 11, fontWeight: '800' },
  modelDownloadLabel: { fontSize: 10, fontWeight: '800', minWidth: 48, textAlign: 'right' },
  modelOptionTitle: { fontSize: 14, fontWeight: '700' },
  modelOptionText: { fontSize: 12, lineHeight: 17, marginTop: 3 },
  modelSearchBox: { height: 43, borderWidth: 1, borderRadius: 12, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 11, marginBottom: 12 },
  modelSearchInput: { flex: 1, fontSize: 13, paddingHorizontal: 8, paddingVertical: 0 },
  modelSectionLabel: { fontSize: 10, fontWeight: '800', letterSpacing: 1.1, marginBottom: 8 },
  modelCatalog: { maxHeight: 210, marginBottom: 10 },
  modelCatalogItem: { minHeight: 64, borderWidth: 1, borderRadius: 14, padding: 9, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  directDownload: { borderWidth: 1, borderRadius: 16, padding: 12, gap: 10 },
  modelUrlInput: { height: 43, borderWidth: 1, borderRadius: 11, paddingHorizontal: 11, fontSize: 13 },
  modelDownloadButton: { minHeight: 42, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  modelDownloadButtonText: { color: '#FFFFFF', fontSize: 13, fontWeight: '700' },
  modelNotice: { fontSize: 11, lineHeight: 16, marginTop: 14 },
  modelBrowseLink: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 14 },
  modelBrowseLinkText: { fontSize: 13, fontWeight: '600' },
  settingsSheet: { maxHeight: '92%', borderTopLeftRadius: 26, borderTopRightRadius: 26, paddingHorizontal: 18, paddingTop: 10, paddingBottom: 24 },
  settingsHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 6 },
  settingsSubtitle: { fontSize: 13, marginTop: -8, marginBottom: 10 },
  settingsSection: { fontSize: 10, fontWeight: '800', letterSpacing: 1.2, marginTop: 17, marginBottom: 8, paddingHorizontal: 3 },
  settingsCard: { borderWidth: 1, borderRadius: 16, padding: 13 },
  settingRow: { minHeight: 42, flexDirection: 'row', alignItems: 'center' },
  settingCopy: { flex: 1 },
  settingTitle: { fontSize: 13, fontWeight: '700' },
  settingDescription: { fontSize: 11, lineHeight: 16, marginTop: 3 },
  settingInline: { borderTopWidth: StyleSheet.hairlineWidth, marginTop: 12, paddingTop: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  settingValueButton: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  settingValue: { fontSize: 12, fontWeight: '700' },
  aboutNote: { fontSize: 11, lineHeight: 16, marginTop: 12, paddingTop: 12, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#454545' },
  toolSheet: {
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 30,
    shadowOpacity: 0.15,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: -4 },
  },
  sheetHandle: { alignSelf: 'center', width: 34, height: 4, borderRadius: 2, marginBottom: 18 },
  sheetTitle: { fontSize: 18, fontWeight: '700', marginBottom: 16 },
  toolsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  toolItem: { width: '31%', minHeight: 92, borderWidth: 1, borderRadius: 18, alignItems: 'center', justifyContent: 'center', gap: 8, paddingHorizontal: 6 },
  toolIcon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  toolLabel: { fontSize: 12, fontWeight: '700' },
});
